name: Erlang CI

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.0.7

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
    - name: Release
      run: rebar3 release
